"use client";

import { viewerFetch } from "./viewer-request";

// One speech service, one queue, one voice. Microsoft Edge neural speech is
// generated by our authenticated Vercel route; the browser only decodes a
// small MP3 segment, so there is no model download or inference warm-up.

type SpeechBatch = {
  generation: number;
  text: string;
  segments: string[];
  onEnergy: (energy: number) => void;
  onStart?: () => void;
  onEnd?: () => void;
  settled: boolean;
  resolve: () => void;
};

type AudioResult = { audio: ArrayBuffer };

const ECHO_GUARD_TAIL_MS = 45_000;
const REQUEST_TIMEOUT_MS = 7_000;
const FIRST_SPEECH_CHUNK_MIN = 12;
const MAX_SPEECH_CHUNK_CHARS = 56;
const MAX_MEMORY_AUDIO_SEGMENTS = 12;
const TTS_ENGINE = "edge-neural-ryan-gb";

let generation = 0;
let audioContext: AudioContext | null = null;
let currentSource: AudioBufferSourceNode | null = null;
let finishCurrentPlayback: (() => void) | null = null;
let draining = false;
let activeBatch: SpeechBatch | null = null;
let queue: SpeechBatch[] = [];
const pendingRequests = new Set<AbortController>();
const audioCache = new Map<string, AudioResult>();
const synthesisInFlight = new Map<string, Promise<AudioResult>>();
type Recent = { text: string; until: number };
let recentUtterances: Recent[] = [];

const words = (text: string) =>
  text.toLowerCase().replace(/[^a-z0-9\s']/g, " ").split(/\s+/).filter((word) => word.length > 1);

function setTtsStatus(status: "loading" | "ready" | "buffering" | "speaking" | "unavailable") {
  if (typeof document === "undefined") return;
  document.documentElement.dataset.jarvisTts = status;
  document.documentElement.dataset.jarvisTtsEngine = TTS_ENGINE;
  if (status !== "unavailable") delete document.documentElement.dataset.jarvisTtsFailure;
}

function reportFailure(error: unknown) {
  const message = String(error).replace(/\s+/g, " ").slice(0, 240);
  setTtsStatus("unavailable");
  if (typeof document === "undefined") return;
  document.documentElement.dataset.jarvisTtsFailure = message;
  void viewerFetch("/api/incident", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({
      signature: "client:edge-tts",
      message: `Jarvis's Edge neural voice failed: ${message}`,
    }),
  }).catch(() => {});
}

function ensureAudioContext(): AudioContext {
  if (!audioContext) {
    const Context = window.AudioContext
      ?? (window as typeof window & { webkitAudioContext?: typeof AudioContext }).webkitAudioContext;
    if (!Context) throw new Error("Web Audio is unavailable in this browser");
    audioContext = new Context({ latencyHint: "interactive" });
  }
  return audioContext;
}

/** Resume Web Audio synchronously from a genuine pointer/key interaction. */
export function unlockSpeechPlayback(): void {
  if (typeof window === "undefined") return;
  try {
    const context = ensureAudioContext();
    if (context.state === "suspended") void context.resume().catch(reportFailure);
  } catch (error) {
    reportFailure(error);
  }
}

/** Warm only the small Vercel route bundle. There is no browser model to load. */
export async function warm(): Promise<void> {
  if (typeof window === "undefined") return;
  setTtsStatus("ready");
  await viewerFetch("/api/tts", { method: "GET", cache: "no-store" }).catch(() => undefined);
}

function trackUtterance(text: string, durationMs: number) {
  const now = Date.now();
  recentUtterances = recentUtterances.filter((row) => row.until > now);
  recentUtterances.push({ text, until: now + durationMs + ECHO_GUARD_TAIL_MS });
}

export function isEchoOfTts(input: string): boolean {
  const now = Date.now();
  recentUtterances = recentUtterances.filter((row) => row.until > now);
  const inputWords = words(input);
  if (!inputWords.length) return false;
  for (const row of recentUtterances) {
    const spoken = new Set(words(row.text));
    if (!spoken.size) continue;
    const matches = inputWords.filter((word) => spoken.has(word)).length;
    if (inputWords.length <= 2 && matches === inputWords.length) return true;
    if (matches / inputWords.length >= 0.65) return true;
  }
  return false;
}

export function completeSpeechPrefix(input: string): string {
  const matches = [...input.matchAll(/[.!?](?:[”"')\]]+)?(?=\s|$)|\n\s*\n/g)];
  const last = matches.at(-1);
  if (!last || last.index == null) return "";
  const prefix = input.slice(0, last.index + last[0].length);
  return prefix.trim().length >= 18 ? prefix : "";
}

export function normalizeSpeechText(input: string): string {
  let text = input.normalize("NFKC").replace(/\r\n?/g, "\n");
  text = text
    .replace(/\[([^\]]+)]\((?:https?:\/\/)[^)]+\)/gi, "$1")
    .replace(/https?:\/\/\S+/gi, "the link")
    .replace(/^\s*#{1,6}\s+/gm, "")
    .replace(/^\s*(?:[-*•▪◦]|\d+[.)])\s+/gm, "")
    .replace(/[`*]+/g, "")
    .replace(/_/g, " ")
    .replace(/\n+/g, ". ")
    .replace(/(\d)\s*[–—]\s*(\d)/g, "$1 to $2")
    .replace(/\s*[–—]\s*/g, ", ")
    .replace(/\s+--?\s+/g, ", ")
    .replace(/--+/g, ", ")
    .replace(/(?:\.{3,}|…+)(?=\s*(?:$|[”"']))/g, ".")
    .replace(/(?:\.{3,}|…+)/g, ", ")
    .replace(/\s+\/\s+/g, " or ")
    .replace(/\s*&\s*/g, " and ")
    .replace(/([!?])\1+/g, "$1")
    .replace(/\s+([,.;:!?])/g, "$1")
    .replace(/,\s*([.!?])/g, "$1")
    .replace(/(?:\.\s*){2,}/g, ". ")
    .replace(/[ \t]{2,}/g, " ")
    .trim();
  if (!text) return "";
  if (/[,:;]\s*$/.test(text)) text = text.replace(/[,:;]\s*$/, ".");
  else if (!/[.!?][”"')\]]?$/.test(text)) text += ".";
  return text;
}

export function sentences(text: string): string[] {
  const speech = normalizeSpeechText(text);
  const result: string[] = [];
  let buffer = "";

  const appendBounded = (value: string) => {
    let remaining = value.trim();
    while (remaining.length > MAX_SPEECH_CHUNK_CHARS) {
      const window = remaining.slice(0, MAX_SPEECH_CHUNK_CHARS + 1);
      const boundary = window.lastIndexOf(" ");
      const cut = boundary >= Math.floor(MAX_SPEECH_CHUNK_CHARS * 0.58)
        ? boundary
        : MAX_SPEECH_CHUNK_CHARS;
      result.push(remaining.slice(0, cut).trim());
      remaining = remaining.slice(cut).trim();
    }
    if (remaining) result.push(remaining);
  };

  for (const part of speech.split(/(?<=[.!?;:])\s+|(?<=,)\s+(?=\S)/)) {
    buffer = buffer ? `${buffer} ${part}` : part;
    if (buffer.length >= FIRST_SPEECH_CHUNK_MIN) {
      appendBounded(buffer);
      buffer = "";
    }
  }
  if (buffer.trim()) appendBounded(buffer);
  return result;
}

export function speechPauseMs(text: string): number {
  const ending = text.trim();
  if (/[?!][”"')\]]?$/.test(ending)) return 150;
  if (/\.[”"')\]]?$/.test(ending)) return 120;
  if (/[;:][”"')\]]?$/.test(ending)) return 70;
  if (/,[”"')\]]?$/.test(ending)) return 35;
  return 0;
}

function speechSpeed(text: string): number {
  const tone = text.toLowerCase();
  if (/\b(urgent|careful|risk|serious|honestly|weak plan)\b/.test(tone)) return 1.03;
  if (/\b(sorry|rough|tired|stressed|gentle)\b/.test(tone)) return 0.98;
  if (/\b(ha|haha|brilliant|let's go|excited|love it)\b/.test(tone)) return 1.16;
  return 1.1;
}

async function requestAudio(text: string, expectedGeneration: number, attempt = 0): Promise<AudioResult> {
  if (expectedGeneration !== generation) throw new Error("speech cancelled");
  const controller = new AbortController();
  pendingRequests.add(controller);
  const timeout = window.setTimeout(() => controller.abort("Edge TTS timed out"), REQUEST_TIMEOUT_MS);
  try {
    const response = await viewerFetch("/api/tts", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ text, speed: speechSpeed(text) }),
      cache: "no-store",
      signal: controller.signal,
    });
    if (!response.ok) {
      const detail = await response.json().catch(() => null) as { error?: unknown } | null;
      throw new Error(String(detail?.error ?? `Edge TTS returned ${response.status}`));
    }
    const audio = await response.arrayBuffer();
    if (audio.byteLength < 512) throw new Error("Edge TTS returned empty audio");
    return { audio };
  } catch (error) {
    if (attempt === 0 && expectedGeneration === generation) {
      await new Promise((resolve) => setTimeout(resolve, 60));
      return requestAudio(text, expectedGeneration, 1);
    }
    throw error;
  } finally {
    window.clearTimeout(timeout);
    pendingRequests.delete(controller);
  }
}

function rememberAudio(key: string, result: AudioResult): AudioResult {
  audioCache.delete(key);
  audioCache.set(key, result);
  while (audioCache.size > MAX_MEMORY_AUDIO_SEGMENTS) {
    const oldest = audioCache.keys().next().value;
    if (typeof oldest !== "string") break;
    audioCache.delete(oldest);
  }
  return result;
}

async function synthesize(text: string, expectedGeneration: number): Promise<AudioResult> {
  const key = `${speechSpeed(text)}:${text}`;
  const cached = audioCache.get(key);
  if (cached) return cached;
  const existing = synthesisInFlight.get(key);
  if (existing) return existing;
  const request = requestAudio(text, expectedGeneration).then((result) => rememberAudio(key, result));
  synthesisInFlight.set(key, request);
  try {
    return await request;
  } finally {
    if (synthesisInFlight.get(key) === request) synthesisInFlight.delete(key);
  }
}

async function playAudio(result: AudioResult, expectedGeneration: number, onEnergy: (energy: number) => void) {
  if (expectedGeneration !== generation) return false;
  const context = ensureAudioContext();
  if (context.state === "suspended") await context.resume();
  const buffer = await context.decodeAudioData(result.audio.slice(0));
  if (expectedGeneration !== generation) return false;
  const source = context.createBufferSource();
  const analyser = context.createAnalyser();
  analyser.fftSize = 128;
  source.buffer = buffer;
  source.connect(analyser);
  analyser.connect(context.destination);
  currentSource = source;
  setTtsStatus("speaking");
  return new Promise<boolean>((resolve) => {
    let settled = false;
    const levels = new Uint8Array(analyser.frequencyBinCount);
    const energyTimer = setInterval(() => {
      analyser.getByteFrequencyData(levels);
      const mean = levels.reduce((sum, value) => sum + value, 0) / Math.max(1, levels.length);
      onEnergy(Math.min(1, mean / 110));
    }, 48);
    const finish = (played: boolean) => {
      if (settled) return;
      settled = true;
      clearInterval(energyTimer);
      onEnergy(0);
      if (currentSource === source) currentSource = null;
      if (finishCurrentPlayback === stop) finishCurrentPlayback = null;
      source.disconnect();
      analyser.disconnect();
      resolve(played);
    };
    const stop = () => finish(false);
    finishCurrentPlayback = stop;
    source.onended = () => finish(true);
    source.start();
  });
}

function settle(batch: SpeechBatch, callEnd: boolean) {
  if (batch.settled) return;
  batch.settled = true;
  if (callEnd) batch.onEnd?.();
  batch.resolve();
}

export function stopSpeaking() {
  generation++;
  for (const controller of pendingRequests) controller.abort("speech cancelled");
  pendingRequests.clear();
  const abandoned = queue;
  queue = [];
  for (const batch of abandoned) settle(batch, false);
  if (activeBatch) settle(activeBatch, false);
  try { currentSource?.stop(); } catch { /* already ended */ }
  finishCurrentPlayback?.();
  currentSource = null;
  finishCurrentPlayback = null;
  setTtsStatus("ready");
  void import("./wakeword").then((module) => module.setSuppressed?.(false)).catch(() => {});
}

export function isSpeaking() {
  return Boolean(currentSource);
}

export async function speak(
  text: string,
  onEnergy: (energy: number) => void,
  onStart?: () => void,
  onEnd?: () => void,
): Promise<void> {
  const speech = normalizeSpeechText(text);
  if (typeof window === "undefined" || !speech) {
    onEnd?.();
    return;
  }
  trackUtterance(speech, Math.min(90_000, speech.length * 70));
  const done = new Promise<void>((resolve) => {
    queue.push({
      generation,
      text: speech,
      segments: sentences(speech),
      onEnergy,
      onStart,
      onEnd,
      settled: false,
      resolve,
    });
  });
  void drainSpeechQueue();
  await done;
}

async function drainSpeechQueue(): Promise<void> {
  if (draining) return;
  draining = true;
  try {
    while (queue.length) {
      const batch = queue.shift()!;
      activeBatch = batch;
      void import("./wakeword").then((module) => module.setSuppressed?.(true, /jarvis/i.test(batch.text))).catch(() => {});
      let started = false;
      let next = batch.segments[0] ? synthesize(batch.segments[0], batch.generation) : null;
      try {
        for (let index = 0; next && index < batch.segments.length; index++) {
          if (batch.generation !== generation) break;
          setTtsStatus("buffering");
          const audio = await next;
          if (batch.generation !== generation) break;
          next = batch.segments[index + 1]
            ? synthesize(batch.segments[index + 1], batch.generation)
            : null;
          if (!started) {
            started = true;
            batch.onStart?.();
          }
          const played = await playAudio(audio, batch.generation, batch.onEnergy);
          if (!played || batch.generation !== generation) break;
          const pause = speechPauseMs(batch.segments[index]);
          if (pause) await new Promise((resolve) => setTimeout(resolve, pause));
        }
        if (batch.generation === generation) {
          setTtsStatus("ready");
          settle(batch, true);
        } else {
          settle(batch, false);
        }
      } catch (error) {
        if (batch.generation === generation) {
          reportFailure(error);
          settle(batch, true);
        } else {
          settle(batch, false);
        }
      } finally {
        activeBatch = null;
      }
    }
  } finally {
    draining = false;
    if (!activeBatch && queue.length === 0) {
      setTimeout(() => {
        if (!currentSource) {
          void import("./wakeword").then((module) => module.setSuppressed?.(false)).catch(() => {});
        }
      }, 900);
    }
    if (queue.length) void drainSpeechQueue();
  }
}
