import { describe, expect, it } from "vitest";
import {
  FOREGROUND_CONCURRENCY,
  canClaimForegroundTurn,
  FOREGROUND_ADMISSION_RESERVE_MS,
  FOREGROUND_DURABLE_RECOVERY_CRON,
  FOREGROUND_HANDOFF_OVERLAP_MS,
  FOREGROUND_LANE_MAX_DURATION_SECONDS,
  FOREGROUND_MAX_DURATION_SECONDS,
  FOREGROUND_PROCESS_EXIT_RESERVE_MS,
  FOREGROUND_QUEUE,
  FOREGROUND_SESSION_RENEWAL_RESERVE_MS,
  FOREGROUND_SESSION_STARTUP_RESERVE_MS,
  FOREGROUND_TURN_VALIDITY_RESERVE_MS,
  FOREGROUND_TURN_TIMEOUT_MS,
} from "./foreground-policy";
import {
  CODEX_CONSUMER_REFRESH_GUARD_MS,
  PINNED_CODEX_INTERNAL_REFRESH_GUARD_MS,
} from "./subscription-validity";

describe("foreground conversation policy", () => {
  it("keeps one authoritative warm foreground owner with a bounded handoff", () => {
    expect(FOREGROUND_QUEUE).toBe("jarvis-foreground");
    expect(FOREGROUND_CONCURRENCY).toBe(1);
    expect(FOREGROUND_DURABLE_RECOVERY_CRON).toBe("*/5 * * * *");
    expect(FOREGROUND_TURN_TIMEOUT_MS).toBeLessThanOrEqual(3 * 60_000);
    expect(FOREGROUND_MAX_DURATION_SECONDS).toBe(4 * 60 * 60);
    expect(FOREGROUND_ADMISSION_RESERVE_MS).toBeGreaterThan(FOREGROUND_TURN_TIMEOUT_MS);
    expect(FOREGROUND_SESSION_STARTUP_RESERVE_MS).toBeGreaterThan(0);
    expect(PINNED_CODEX_INTERNAL_REFRESH_GUARD_MS).toBeGreaterThanOrEqual(5 * 60_000);
    expect(CODEX_CONSUMER_REFRESH_GUARD_MS - PINNED_CODEX_INTERNAL_REFRESH_GUARD_MS)
      .toBeGreaterThanOrEqual(60_000);
    expect(FOREGROUND_TURN_VALIDITY_RESERVE_MS).toBe(
      FOREGROUND_ADMISSION_RESERVE_MS + CODEX_CONSUMER_REFRESH_GUARD_MS,
    );
    expect(FOREGROUND_SESSION_RENEWAL_RESERVE_MS).toBe(
      FOREGROUND_ADMISSION_RESERVE_MS + FOREGROUND_SESSION_STARTUP_RESERVE_MS
        + CODEX_CONSUMER_REFRESH_GUARD_MS,
    );
    expect(FOREGROUND_HANDOFF_OVERLAP_MS).toBeGreaterThan(FOREGROUND_ADMISSION_RESERVE_MS);
    expect(FOREGROUND_PROCESS_EXIT_RESERVE_MS).toBeGreaterThan(0);
    expect(FOREGROUND_LANE_MAX_DURATION_SECONDS).toBeGreaterThan(FOREGROUND_MAX_DURATION_SECONDS);
  });

  it("leaves a turn durable for the successor at the admission boundary", () => {
    expect(canClaimForegroundTurn(FOREGROUND_ADMISSION_RESERVE_MS)).toBe(true);
    expect(canClaimForegroundTurn(FOREGROUND_ADMISSION_RESERVE_MS - 1)).toBe(false);
  });
});
